apiVersion: v1
clusters:
  - cluster:
      server: https://EB24AA8D896817E2FD67879B91642C0F.gr7.us-east-1.eks.amazonaws.com
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJQnJJS3NBTGlZNTh3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TXpBNU1UVXlNekkzTkRWYUZ3MHpNekE1TVRJeU16STNORFZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURLc0FnTnY4K0I5QzB2R2RpZU9kQ3lQR29UeWdzZmV2OVk1YmdDSlZ3RTRjcmlQN0hKalVJa25YRHgKcTY4Qi8vaHltbi9Qd25JVHVZeGFqbVNyTE5xTVVESE1WbVZ3VVVvMitOYm5kWjRCMGFURTFuc1kzZlF2elB1Vgp4TU0zQ2RqakVhTldNcko0Z1lNQ0hWTHNINVl3NmQ2dnA3Z2ltR2Z0Tm1sY01OZGM2bnhFODRQN2VZWVpWWWxBCldHRXBQZnVxZFFPOUVWMFNEdldnSTBDUkJpbmF6MVluMTFRSS9zUG01UHg5QTNlZkFjZ1pHY1dGSGwzUE0va1cKYWFQQk9XWkVRZGExUVlzMjNZQTRiUnpNQmZCdTVBUDBTS01DMUlUWHBNY1BENUJOSzUrcDBlczJOdEFqVVVweQpqRFlnclpZR00vdmkzbFE5clBHdHBhTnJEYTgxQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTY2NSNEtzWUU4QWswSGJKZ3oxTHNrck5DRDNEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQlZxRDVkUEIzRwo0UitLVVd2em1Yc2pJZWcvanB4bFJkdVkzeThwb0o3S2lrSlpXR0F0cmhnUTljOW1TS1NRQ05xSU00eERCOVBwCm96OGdOa1hnUDNQWDIyb3lKQ1RVRXdXNzlnREp4b1ZKVmhUVVhMQ0c5WHZJamZ5VVg5TGtKcmpHYWkwaDdEUlQKRE5TSGJFb2Z3RTFLem9vTWxwQ3NxRVc4T1p1djBGNk5HS0VQOEZtTC94T3JWWlA1OVFRZXExYm5tZUhjd0VueApTdUhOZnpaL25xYkx4WnpFN2dUMDh4VlFyZE5QY0NUMVNWdDhCR1dFTEN6dHc0TVgrb0hjaDdRVmZPbUZkYmNHCmQ2bldLQXZJRFdtOXNWaG5jY3IydXlpZUcxUVBkY2RrSm9PKzg1dkJic2h0d1NxVzZNdTFBencxbDFLQllHTXkKdGM3VlFhVmJUeTNHCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    name: kubernetes
contexts:
  - context:
      cluster: kubernetes
      user: aws
    name: aws
current-context: aws
kind: Config
users:
  - name: aws
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        command: aws
        args:
          - eks
          - get-token
          - --cluster-name
          - eks-i-cluster-eksCluster-63257ee
          - --output
          - json
        env:
          - name: KUBERNETES_EXEC_INFO
            value: '{"apiVersion": "client.authentication.k8s.io/v1beta1"}'

